help_file = {
    'server': 'Skonfiguruj świat, na którym bot powinien grać',
    'server.server': 'Endpoint serwera do użycia (świat)',
    'server.endpoint': 'Serwer endpoint do użycia (pełny URL)',
    'server.server_on_twstats': 'Czy serwer jest wymieniony na twstats.com?',
    'bot': 'Ustaw globalne zmienne konfiguracji bota',
    'bot.active_hours': 'Godziny, w których bot powinien używać active_delay (nie wpływa na timing ataków)',
    'bot.delay_factor': 'Współczynnik opóźnienia do użycia 5-7sekund * współczynnik opóźnienia (bardzo niskie współczynniki prawdopodobnie spowodują ban)',
    'bot.active_delay': 'Opóźnienie w sekundach do użycia w aktywnych czasach bota',
    'bot.inactive_delay': 'Opóźnienie w sekundach do użycia w nieaktywnych czasach bota',
    'bot.inactive_still_active': 'Nieaktywny, aby zatrzymać bota z uruchomieniami podczas nieaktywnych czasów',
    'bot.add_new_villages': 'Automatycznie dodaj domyślną konfigurację wsi do nowo zdobytych wsi',
    'bot.village_name_template': 'Szablon do użycia dla nowych wsi, użyj {num} aby ustawić indeks konfiguracji jako nazwę',
    'bot.village_name_number_length': 'Długość numeru, niższe będą prefiksowane zerami',
    'bot.auto_set_village_names': 'Automatycznie ustaw nazwy wsi',
    'bot.user_agent': 'Ustaw to na agent przeglądarki używanego przez twoją sesję (w innym wypadku może spowodować ban)',
    'building.manage_buildings': 'Automatycznie zarządzaj budynkami',
    'building': 'Automatyczne tworzenie budynków',
    'building.default': 'Domyślny szablon do użycia, konfiguracje wsi zastępują tę zmienną',
    'building.max_lookahead': 'Maksymalna liczba elementów w kolejce do sprawdzenia przed zatrzymaniem',
    'building.max_queued_items': 'Maksymalna liczba elementów w kolejce, domyślnie: 2 premium: 5',
    'units': 'Włącz automatyczną rekrutację jednostek',
    'units.recruit': 'Automatycznie rekrutuj jednostki',
    'units.upgrade': 'Automatycznie ulepszaj jednostki (tylko dla systemów hut 1-3, 1-10)',
    'units.default': 'Domyślny szablon do tworzenia jednostek (templates/troops)',
    'units.batch_size': 'Liczba jednostek do próby utworzenia w jednym przebiegu, zwiększ to w grze końcowej',
    'units.manage_defence': 'Zarządzaj obroną między wsiami (eksperymentalne)',
    'units.remove_manual_queued': 'Usuń ręcznie zakolejkowane wpisy rekrutacji',
    'units.randomize_unit_queue': 'Randomizuj kolejkę jednostek, pozwala na większą różnorodność jednostek',
    'farms': 'Automatyczne farmeowanie pobliskich wsi barbarzyńskich',
    'farms.farm': 'Włącz automatyczne farmeowanie',
    'farms.min_points': 'Minimalna liczba punktów wsi do ataku (również sprawdza custom_farms)',
    'farms.max_points': 'Maksymalna liczba punktów wsi do ataku (również sprawdza custom_farms)',
    'farms.find_player_owned': 'Automatycznie atakuj wszystkie wsie należące do gracza (niebezpieczne)',
    'farms.search_radius': 'Maksymalny promień wsi do ataku (pola)',
    'farms.default_away_time': 'Domyślny czas w sekundach do czekania przed ponownym atakiem na wioskę',
    'farms.full_loot_away_time': 'Czas oczekiwania dla wsi z wysokim zyskiem zasobów',
    'farms.low_loot_away_time': 'Czas oczekiwania dla wsi z niskim zyskiem zasobów',
    'farms.max_farms': 'Liczba pobliskich wsi do sprawdzenia',
    'farms.attack_higher_points': 'Jeśli włączone, wsie z wyższymi punktami niż bieżąca będą automatycznie ignorowane',
    'farms.force_scout_if_available': 'Będzie atakować tylko wsie, które zostały wcześniej zaatakowane lub będzie je automatycznie zwiadowcować',
    'farms.farm_scout_amount': 'Ustawia liczbę zwiadowców używanych do określenia, czy wieś jest bezpieczna do farmeowania',
    'farms.farm_assistant': 'Użyj okna asystenta farmy (A/B/C) zamiast standardowego ataku place',
    'farms.farm_assistant_button': 'Wybierz ikonę farm assistant do użycia: A, B, C lub AUTO',
    'farms.farm_assistant_wall_threshold': 'Jeśli AUTO, użyj A dla celu o muru >= tej wartości, w przeciwnym razie B',
    'farms.farm_assistant_min_wall': 'Minimalny poziom muru celu do farm assistant',
    'farms.farm_assistant_max_wall': 'Maksymalny poziom muru celu do farm assistant',
    'market': 'Automatyczne zarządzanie handlem na targu',
    'market.auto_trade': 'Włącz zautomatyzowany handel',
    'market.max_trade_duration': 'Maksymalny czas trwania handlu (godziny)',
    'market.auto_remove': 'Automatycznie usuń istniejący lub wygasłe transakcje',
    'market.trade_multiplier': 'Ustaw na true, jeśli świat obsługuje nierówne współczynniki handlu',
    'market.trade_multiplier_value': 'Wartość mnożnika (niższa = większy zysk)',
    'market.trade_max_per_hour': 'Liczba transakcji, które bot może wykonać w ciągu 1 godziny',
    'world.knight_enabled': 'Świat ma włączone rycerzy',
    'world.flags_enabled': 'Pozwala na automatyczne zarządzanie flagami (ulepszanie i obrona)',
    'world.quests_enabled': 'Świat ma włączone zadania (bot będzie je automatycznie wykonywać)',
    'world.trade_for_premium': 'Świat ma włączony rynek premium (robienie tego zbyt często może spowodować ban)',
    'world.archers_enabled': 'Czy łuczniki / maszerowie są włączeni na świecie',
    'world.building_destruction_enabled': 'Czy taran / katapulty są włączone na świecie',
    'village_template': 'Domyślny szablon dla wsi do użycia',
    'village.building': 'Zastąp szablon budynków',
    'village.units': 'Zastąp szablon rekrutacji / farmy',
    'village.managed': 'Wieś powinna być zarządzana przez bota',
    'village.scout_first': 'Wieś powinna zwiadowcować wsie przed farmeowaniem',
    'village.additional_farms': 'Lista wsi do uwzględnienia w procesie farmeowania (nie wymaga active find_player_owned)',
    'village.prioritize_building': 'Nie rekrutuj, jeśli budowniczy nie ma wystarczających zasobów',
    'village.prioritize_snob': 'Nie rekrutuj, jeśli szlachta nie ma wystarczających zasobów',
    'village.trade_for_premium': 'Handluj pozostałymi zasobami za punkty premium (wymaga włączenia opcji globalnej)',
    'village.gather_enabled': 'Używa pozostałych jednostek do zbierania dodatkowych zasobów, jeśli opcja jest włączona na świecie',
    'village.gather_selection': 'Operacja zbierania do wykonania (muszą być najpierw odblokowane)',
    'village.snobs': 'Liczba szlachty do utworzenia w bieżącej wsi',
    'village.evacuate_fragile_units_on_attack': 'Automatycznie ewakuuj delikatne jednostki (siekiera, szlachta) do pobliskich bezpiecznych wsi w przypadku ataku',
    'village.support_others': 'Pozwala na wysyłanie automatycznego wsparcia',
    'village.support_others_factor': 'Współczynnik jednostek do użycia w operacji wsparcia (tylko jednostki defensywne)',
    'village.support_others_max_villages': 'Maksymalna liczba wsi do wysłania wsparcia (łącznie 2 * 25% wojsk)',
    'village.request_support_on_attack': 'Pozwala na automatyczne żądanie jednostek wsparcia'
}
buildings = ["pałac", "koszary", "stajnia", "wieża", "huta", "garaż", "place", "pomnik", "targ", "drewno",
             "kamień", "żelazo", "farma", "ukrycie", "mur", "szlachta", "kościół"]
